version: "3.2"
services:
  main:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATASTORE_EMULATOR_HOST: datastore:8081
      DATASTORE_PROJECT_ID: the-blue-alliance-slack
    env_file: .env
    volumes:
      - ".:/usr/src/app"
  datastore:
    image: google/cloud-sdk
    command: gcloud beta emulators datastore start --host-port 0.0.0.0:8081
    environment:
      CLOUDSDK_CORE_PROJECT: the-blue-alliance-slack
    expose:
      - 8081
    volumes:
      - "datastore_volume:/root/.config/gcloud/emulators/datastore/WEB-INF/appengine-generated"
  ngrok:
    image: wernight/ngrok
    env_file: .ngrok.env
    environment:
      NGROK_PORT: main:3000
    ports:
      - "3001:4040"
  dsui:
    build: dsui/
    environment:
      DATASTORE_PROJECT_ID: the-blue-alliance-slack
      DATASTORE_EMULATOR_HOST: datastore:8081
    ports:
      - "3002:3000"
volumes:
  datastore_volume:
